# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
#  config.vm.network "private_network", type: "dhcp"
	config.vm.network "private_network", ip: "192.168.33.17"
	config.vm.hostname = "dockerinaction"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "4"  
   #This is for a hard drive of 20G
   # dataDisk1 = './dataDisk1.vdi'
    #dataDisk2 = './dataDisk2.vdi'

   # if not File.exists?(dataDisk1)
      # vb.customize ['createhd', '--filename', dataDisk1, '--variant', 'Fixed', '--size', 10 * 1024]
    # end
	 # if not File.exists?(dataDisk2)
       # vb.customize ['createhd', '--filename', dataDisk2, '--variant', 'Fixed', '--size', 10 * 1024]
     # end
	# adding a SATA controller that allows 1 hard drives
	# vb.customize ['storagectl', :id, '--name', 'SATA Controller', '--add', 'sata', '--portcount', 2]
	# vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', dataDisk1]
	 # vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', dataDisk2]



 end
config.vm.provision "shell", inline: <<-SHELL
   sudo su
   echo "root" | passwd --stdin root
   echo "Configuring SSH"
   sed -i 's/#PermitRootLogin/PermitRootLogin/' /etc/ssh/sshd_config
   sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
   sed -i 's/PasswordAuthentication no/#PasswordAuthentication no/' /etc/ssh/sshd_config
   #echo "Configured SSH"
   #echo "Installing VDO"
   yum install epel-release vdo kmod-vdo -y
   #echo "VDO Successfully installed"
   systemctl restart sshd.service
   SHELL

  


end
