# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
#  config.vm.network "private_network", type: "dhcp"
	config.vm.network "private_network", ip: "192.168.33.18"
	config.vm.hostname = "terraform"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "2"
 end
config.vm.provision "shell", inline: <<-SHELL
   sudo su
   echo "root" | passwd --stdin root
   echo "Configuring SSH"
   sed -i 's/#PermitRootLogin/PermitRootLogin/' /etc/ssh/sshd_config
   sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
   sed -i 's/PasswordAuthentication no/#PasswordAuthentication no/' /etc/ssh/sshd_config
   echo "Configured SSH"
   systemctl restart sshd.service
   curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
   python get-pip.py
   pip install awscli
   yum install -y wget
   yum install -y unzip
   wget https://releases.hashicorp.com/terraform/0.12.2/terraform_0.12.2_linux_amd64.zip
   unzip ./terraform_0.12.2_linux_amd64.zip -d /usr/local/bin
   SHELL
end
