# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
#  config.vm.network "private_network", type: "dhcp"
	config.vm.network "private_network", ip: "192.168.33.35"
	config.vm.hostname = "ubuntu2"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "512"
    vb.cpus = "2"  
 end
   config.vm.provision "shell", inline: <<-SHELL
   sudo su
   echo "root" | passwd --stdin root
   sed -i 's/#PermitRootLogin/PermitRootLogin/' /etc/ssh/sshd_config
   SHELL




end
