# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
#  config.vm.network "private_network", type: "dhcp"
	config.vm.network "private_network", ip: "192.168.33.10"
	config.vm.hostname = "firstvagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
    vb.cpus = "4"  
 end
config.vm.provision "shell", inline: <<-SHELL
sudo su
   echo "root" | passwd --stdin root
   echo "Configuring SSH"
   sed -i 's/#PermitRootLogin/PermitRootLogin/' /etc/ssh/sshd_config
   sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
   sed -i 's/PasswordAuthentication no/#PasswordAuthentication no/' /etc/ssh/sshd_config
   echo "Configured SSH"
   echo "Installing VDO"
   yum install epel-release vdo kmod-vdo -y
   echo "VDO Successfully installed"
   systemctl restart sshd.service
   SHELL

  


end
